export type MealType = "breakfast" | "lunch" | "dinner";
export type Protein = "chicken" | "fish" | "beef" | "vegetarian" | "seafood" | "turkey";

type Ingredient = {
  item: string;
  quantity?: number;
  unit?: string;
};

export type Recipe = {
  id: string;
  name: string;
  mealType: MealType;
  cuisine: "greek" | "italian" | "turkish" | "spanish" | "moroccan" | "mexican" | "middle eastern" | "french";
  protein: Protein;
  servings: number;
  url: string;
  summary: string;
  ingredients: Ingredient[];
};

export const recipes: Recipe[] = [
  {
    id: "greek-yogurt-honey",
    name: "Greek Yogurt with Honey, Walnuts & Figs",
    mealType: "breakfast",
    cuisine: "greek",
    protein: "vegetarian",
    servings: 2,
    url: "https://www.olivetomato.com/greek-yogurt-with-honey-walnuts-and-figs/",
    summary: "Creamy yogurt topped with honey, toasted walnuts, and seasonal figs for a protein-rich start.",
    ingredients: [
      { item: "plain Greek yogurt", quantity: 2, unit: "cups" },
      { item: "honey", quantity: 2, unit: "tablespoons" },
      { item: "walnuts", quantity: 0.5, unit: "cup" },
      { item: "fresh figs", quantity: 4 },
      { item: "ground cinnamon", quantity: 0.25, unit: "teaspoon" },
    ],
  },
  {
    id: "spanish-pan-con-tomate",
    name: "Pan con Tomate with Olive Oil",
    mealType: "breakfast",
    cuisine: "spanish",
    protein: "vegetarian",
    servings: 2,
    url: "https://www.seriouseats.com/pan-con-tomate-spanish-tomato-bread-recipe",
    summary: "Toasted country bread rubbed with fresh tomato, garlic, and excellent olive oil—Barcelona café style.",
    ingredients: [
      { item: "country bread", quantity: 4, unit: "slices" },
      { item: "ripe tomatoes", quantity: 2 },
      { item: "garlic clove", quantity: 1 },
      { item: "extra-virgin olive oil", quantity: 3, unit: "tablespoons" },
      { item: "sea salt" },
    ],
  },
  {
    id: "med-shakshuka",
    name: "Herbed Spinach Shakshuka",
    mealType: "breakfast",
    cuisine: "middle eastern",
    protein: "vegetarian",
    servings: 3,
    url: "https://www.feastingathome.com/green-shakshuka/",
    summary: "Spinach, herbs, and soft eggs simmered in olive oil for a one-pan brunch staple.",
    ingredients: [
      { item: "eggs", quantity: 6 },
      { item: "baby spinach", quantity: 5, unit: "cups" },
      { item: "parsley", quantity: 0.5, unit: "cup" },
      { item: "cilantro", quantity: 0.25, unit: "cup" },
      { item: "olive oil", quantity: 2, unit: "tablespoons" },
      { item: "green onions", quantity: 3 },
    ],
  },
  {
    id: "greek-chicken-salad",
    name: "Grilled Chicken Greek Salad",
    mealType: "lunch",
    cuisine: "greek",
    protein: "chicken",
    servings: 4,
    url: "https://www.dimitrasdishes.com/greek-grilled-chicken-salad/",
    summary: "Char-grilled oregano chicken over cucumbers, tomatoes, olives, and feta with lemon dressing.",
    ingredients: [
      { item: "chicken breasts", quantity: 1.5, unit: "pounds" },
      { item: "romaine hearts", quantity: 2 },
      { item: "cucumbers", quantity: 2 },
      { item: "cherry tomatoes", quantity: 2, unit: "cups" },
      { item: "kalamata olives", quantity: 0.5, unit: "cup" },
      { item: "feta", quantity: 0.75, unit: "cup" },
      { item: "lemon", quantity: 1 },
      { item: "dried oregano", quantity: 1, unit: "teaspoon" },
    ],
  },
  {
    id: "lentil-lemon-soup",
    name: "Lemon Lentil Soup",
    mealType: "lunch",
    cuisine: "middle eastern",
    protein: "vegetarian",
    servings: 4,
    url: "https://www.themediterraneandish.com/mediterranean-lentil-soup/",
    summary: "Earthy lentils with carrots, cumin, and bright lemon—a meal-prep friendly classic.",
    ingredients: [
      { item: "brown lentils", quantity: 1.5, unit: "cups" },
      { item: "carrots", quantity: 2 },
      { item: "celery stalks", quantity: 2 },
      { item: "onion", quantity: 1 },
      { item: "ground cumin", quantity: 1, unit: "teaspoon" },
      { item: "lemon", quantity: 1 },
    ],
  },
  {
    id: "spanish-garbanzos-spinach",
    name: "Spanish Chickpeas and Spinach",
    mealType: "lunch",
    cuisine: "spanish",
    protein: "vegetarian",
    servings: 3,
    url: "https://spanishsabores.com/espinacas-con-garbanzos-recipe/",
    summary: "Andalusian-style stewed chickpeas with paprika, spinach, and a touch of sherry vinegar.",
    ingredients: [
      { item: "cooked chickpeas", quantity: 3, unit: "cups" },
      { item: "baby spinach", quantity: 6, unit: "cups" },
      { item: "smoked paprika", quantity: 1.5, unit: "teaspoons" },
      { item: "sherry vinegar", quantity: 1, unit: "tablespoon" },
      { item: "garlic cloves", quantity: 3 },
      { item: "olive oil", quantity: 3, unit: "tablespoons" },
    ],
  },
  {
    id: "sicilian-tuna-salad",
    name: "Sicilian Fresh Tuna Salad",
    mealType: "lunch",
    cuisine: "italian",
    protein: "fish",
    servings: 4,
    url: "https://www.greatitalianchefs.com/recipes/tuna-salad-recipe",
    summary: "Seared fresh tuna with capers, olives, and lemon—no canned fish in sight.",
    ingredients: [
      { item: "fresh tuna steaks", quantity: 1, unit: "pound" },
      { item: "capers", quantity: 2, unit: "tablespoons" },
      { item: "kalamata olives", quantity: 0.5, unit: "cup" },
      { item: "cherry tomatoes", quantity: 1.5, unit: "cups" },
      { item: "lemon", quantity: 1 },
      { item: "arugula", quantity: 5, unit: "cups" },
    ],
  },
  {
    id: "herb-salmon-tahini",
    name: "Roasted Salmon with Herb Tahini",
    mealType: "dinner",
    cuisine: "middle eastern",
    protein: "fish",
    servings: 4,
    url: "https://www.themediterraneandish.com/baked-salmon-recipe/",
    summary: "Fresh salmon roasted with garlic, olive oil, and a creamy herb tahini drizzle.",
    ingredients: [
      { item: "fresh salmon fillets", quantity: 1.5, unit: "pounds" },
      { item: "tahini", quantity: 0.25, unit: "cup" },
      { item: "parsley", quantity: 0.5, unit: "cup" },
      { item: "garlic cloves", quantity: 3 },
      { item: "lemon", quantity: 1 },
      { item: "olive oil", quantity: 3, unit: "tablespoons" },
    ],
  },
  {
    id: "chicken-souvlaki",
    name: "Chicken Souvlaki with Tzatziki",
    mealType: "dinner",
    cuisine: "greek",
    protein: "chicken",
    servings: 4,
    url: "https://www.akitchencat.com.au/chicken-souvlaki/",
    summary: "Lemon-oregano chicken skewers served with garlicky tzatziki and warm pita.",
    ingredients: [
      { item: "chicken thighs", quantity: 1.25, unit: "pounds" },
      { item: "pita breads", quantity: 4 },
      { item: "plain yogurt", quantity: 1, unit: "cup" },
      { item: "garlic cloves", quantity: 4 },
      { item: "cucumber", quantity: 1 },
      { item: "lemon", quantity: 1 },
      { item: "dried oregano", quantity: 1.5, unit: "teaspoons" },
    ],
  },
  {
    id: "mushroom-barley-risotto",
    name: "Mushroom & Barley Risotto",
    mealType: "dinner",
    cuisine: "italian",
    protein: "vegetarian",
    servings: 4,
    url: "https://www.loveandlemons.com/mushroom-barley-risotto/",
    summary: "Pearl barley simmered with mushrooms, thyme, and pecorino for a hearty meatless main.",
    ingredients: [
      { item: "pearl barley", quantity: 1.25, unit: "cups" },
      { item: "cremini mushrooms", quantity: 16, unit: "ounces" },
      { item: "vegetable broth", quantity: 5, unit: "cups" },
      { item: "pecorino romano", quantity: 0.5, unit: "cup" },
      { item: "fresh thyme", quantity: 1, unit: "tablespoon" },
      { item: "olive oil", quantity: 2, unit: "tablespoons" },
    ],
  },
  {
    id: "beef-kofta-bulgur",
    name: "Beef Kofta with Bulgur Pilaf",
    mealType: "dinner",
    cuisine: "turkish",
    protein: "beef",
    servings: 4,
    url: "https://turkishstylecooking.com/turkish-kofte-recipe.html",
    summary: "Parsley-studded beef kofta with a tomato bulgur pilaf—your single beef night of the week.",
    ingredients: [
      { item: "ground beef", quantity: 1, unit: "pound" },
      { item: "bulgur", quantity: 1, unit: "cup" },
      { item: "tomato paste", quantity: 1, unit: "tablespoon" },
      { item: "parsley", quantity: 0.5, unit: "cup" },
      { item: "onion", quantity: 1 },
      { item: "ground cumin", quantity: 1, unit: "teaspoon" },
    ],
  },
  {
    id: "provencal-ratatouille-couscous",
    name: "Ratatouille over Herbed Couscous",
    mealType: "dinner",
    cuisine: "french",
    protein: "vegetarian",
    servings: 4,
    url: "https://www.seriouseats.com/classic-french-ratatouille-recipe",
    summary: "Slow-cooked Provençal vegetables spooned over fluffy couscous for a vegetable-forward dinner.",
    ingredients: [
      { item: "eggplant", quantity: 1, unit: "medium" },
      { item: "zucchini", quantity: 2 },
      { item: "red bell pepper", quantity: 1 },
      { item: "tomatoes", quantity: 3 },
      { item: "couscous", quantity: 2, unit: "cups" },
      { item: "basil", quantity: 0.25, unit: "cup" },
    ],
  },
  {
    id: "mexican-citrus-snapper",
    name: "Mexican-Style Citrus Snapper",
    mealType: "dinner",
    cuisine: "mexican",
    protein: "fish",
    servings: 4,
    url: "https://www.mexicoinmykitchen.com/pescado-a-la-veracruzana/",
    summary: "Fresh snapper baked with tomatoes, olives, capers, and citrus for a Veracruz coastal flavor.",
    ingredients: [
      { item: "fresh snapper fillets", quantity: 1.25, unit: "pounds" },
      { item: "roma tomatoes", quantity: 4 },
      { item: "green olives", quantity: 0.5, unit: "cup" },
      { item: "capers", quantity: 1, unit: "tablespoon" },
      { item: "orange", quantity: 1 },
      { item: "garlic cloves", quantity: 3 },
    ],
  },
  {
    id: "moroccan-chickpea-tagine",
    name: "Moroccan Chickpea Tagine",
    mealType: "dinner",
    cuisine: "moroccan",
    protein: "vegetarian",
    servings: 4,
    url: "https://www.cookwithmanali.com/moroccan-chickpea-tagine/",
    summary: "Spiced chickpeas with apricots and squash simmered in a saffron tomato broth.",
    ingredients: [
      { item: "cooked chickpeas", quantity: 3, unit: "cups" },
      { item: "butternut squash", quantity: 3, unit: "cups" },
      { item: "dried apricots", quantity: 0.5, unit: "cup" },
      { item: "tomato paste", quantity: 2, unit: "tablespoons" },
      { item: "ras el hanout", quantity: 1.5, unit: "teaspoons" },
      { item: "vegetable broth", quantity: 2, unit: "cups" },
    ],
  },
];
